---
deployment:
  tasks:
    - export DEPLOYPATH=/home/cvacimot/public_html/resale
    - /bin/cp -a * $DEPLOYPATH
    - cd $DEPLOYPATH
    - npm install --production=false
    - npx prisma generate
    - npm run build
    - mkdir -p tmp
    - touch tmp/restart.txt
